services:
  docling:
    image: ghcr.io/docling-project/docling-serve-cpu:v1.17.0
    environment:
      DOCLING_SERVE_ENABLE_UI: "true"
    ports:
      - "5001:5001"
  tika:
    image: apache/tika:3.2.3.0
    ports:
      - "9998:9998"
    restart: always
  doc-processor:
    build: ./api
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./app/cache:/var/cache/docs
